version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: aidaops/api:latest
    container_name: aidaops_api
    ports:
      - "8000:8000"
    environment:
      - ENV=prod
      - MODEL_DIR=/models
      - DATA_DIR=/data
    volumes:
      - ./models:/models
      - ./data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: aidaops_prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: aidaops_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/dashboards:/etc/grafana/dashboards

volumes:
  grafana-storage:
